### ISSUE TITLE
Support for LOA1

### ISSUE THREAD

**Issue by malcolmhire** [alphagov/passport-verify#42]
Currently, there is no support to use this module with Level 1 of Assurance. 

Looking at the code there is a hardcoded LEVEL_2 within /lib/verify-service-provider-client.ts Line 22 and 44. Need to be able to pass a level to the module, similar to how entityId is passed to the module.

**Comment by richardTowers** [comment]
Level of Assurance is configurable in `v1.1.0` - pass `'LEVEL_1'` into `createStrategy` https://alphagov.github.io/passport-verify/modules/_passport_verify_strategy_.html#createstrategy

**Comment by malcolmhire** [comment]
Great work @richardTowers , we'll be implementing this ASAP. Cheers.
